### ISSUE TITLE
cloudup not working when using email address as login

### ISSUE THREAD

**Issue by jschneider** [alexanderepstein/Bash-Snippets#116]
I tried using cloudup and entered my email address as bitbucket user name.
It tried to login into the server from the email address.
I think there should be some kind of escaping for the "@" part?

**Comment by alexanderepstein** [comment]
One cause might be because http uses @ to split up the credentials from the URL, I think the problem comes up when it goes to create the repository. Even if it were created correctly when you set the remote url it sets it to ```username:passwordbitbucket.org@bitbucket.org/username/repoName```. 
The second instance of the username variable actually **needs** to be a username and cannot be an email. Therefore the remote url will be incorrect.

**Comment by alexanderepstein** [comment]
Does it work when you use your actual bitbucket username?

**Comment by jschneider** [comment]
Yes, of course. It works with my "normal" bitbucket user name without "@"

**Comment by alexanderepstein** [comment]
I  don't think there is much for me to do here. The only fix would be to try to scrape your username from your email, but this seems very unnecessary for the edge case in which the user enters an email instead of a username. If I hear of this again from somebody else I may look into scraping the username (if that is even possible). Thanks for letting me know of this issue :+1:
