### ISSUE TITLE
Meme Generator [New Component]

### ISSUE THREAD

**Issue by navanchauhan** [alexanderepstein/Bash-Snippets#125]
**Issue Label:**
* [ ] Bug
* [ ] New feature
* [ ] Enhancement
* [x] New component

**Description:**
Could we add a simple CLI for generating memes? I already have a program for this, if this idea is ok il make a pull request

**Comment by alexanderepstein** [comment]
I don't mind the idea but after reading the code you use ```xdg-open``` which I am pretty sure that is a platform specific command and will not work on windows 10 bash etc... 

If i had to guess this kind of tool will end up in the extras folder under linux.

**Comment by navanchauhan** [comment]
Well I got it to work on windows 10 by using xming but I’ll try to find an alternative to xdg and eog

**Comment by navanchauhan** [comment]
I have found an alternative, just saving the meme without displaying it in the browser by `wget $url -o meme.jpg`

**Comment by alexanderepstein** [comment]
If you look in the maps tool specifically at [this](https://github.com/alexanderepstein/Bash-Snippets/blob/master/extras/Linux/maps/maps#L118) line of code you will see it is possible to use the the existing httpGet function and save the output to an image file.

Just follow the rules for creating a new tool found in [CONTRIBUTING.md](https://github.com/alexanderepstein/Bash-Snippets/blob/master/CONTRIBUTING.md) the most important part being that you use the skeleton script as a starting point. This will follow the standard used by the rest of the scripts.

 If the method of saving the get response like in the maps tool line of code doesn't work you could resort to using flags to download a file. Flags for this should exist for wget and curl  that allow downloading a file directly although fetch and httpie fall short here. The only change would be to the httpGet function which would make more sense to call it httpDownload or something along those lines for this case and to limit it to wget and curl rather than all 4.

P.S. sorry it takes me so long to answer, school has started up again and my open source work has definitely been forced to take a backseat.

**Comment by navanchauhan** [comment]
Closing this as I have followed your suggestions and am now using httpGet and have made a pull request
