### ISSUE TITLE
ytview not working on Mac 

### ISSUE THREAD

**Issue by SDiamante13** [alexanderepstein/Bash-Snippets#176]
**Issue Label:**
* [x ] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
ytview is not functioning properly. When I run ytview Ed Sheeran and choose a song, VLC Media Player is launched and displays this:

<img width="701" alt="screen shot 2018-09-29 at 10 05 43 pm" src="https://user-images.githubusercontent.com/29823897/46252837-31581600-c434-11e8-95f5-02b58f8d3c28.png">

My player is functioning properly with other media files. Note that this happens for any song that I choose from ytview.

### If its a bug make sure to include this section.
**OS and OS version:**
* [x ] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
10.13.6

**Comment by alexanderepstein** [comment]
Hmm if I had to guess it has something to with the fact that these songs are usually videos that are sponsored by the companies and are therefore are a bit different on youtubes server. Since this method circumvents all ads I think this is their way of blocking you from listening to the song without watching the ads first, in which they would be breaking their contract with the record company.
