### ISSUE TITLE
Created a brew formula

### ISSUE THREAD

**Issue by ChainsawBaby** [alexanderepstein/Bash-Snippets#18]
I have created a brew formula for bash snippets for simpler installation on mac.
https://github.com/Homebrew/homebrew-core/pull/15107

The brew build is failing atm now because this repo is less than 30 days, not sure if it is going to be merged into Brew before 30 days have gone.

The test probably should be improved, because it just tests if **crypt** has been installed, but if the user decided to run the `--without-crypt` option, tests will fail

**Comment by alexanderepstein** [comment]
That's cool I would love to have this be a part of homebrew core, my only concern is that if you install it with homebrew core where does it get installed? Because I would have to account for the location of the tools in the update method I created otherwise it would break my update method if you installed with homebrew (unless I get to choose where the file is installed).

I don't really know any Ruby so I don't think I can write real tests for the tools themselves. If you are willing to write the tests and if homebrew won't break my update method (if I readjust to the new install location) I would love to have this be a part of homebrew when the repostiory matures to 30+ days

**Comment by ChainsawBaby** [comment]
They get installed to /usr/local/bin, or, they get linked there. Regarding updating, brew takes care of that. Because it downloads the latest released version from git.

If you see my screenshot, I have v1.5.0 installed, and then I run brew upgrade, it updates bash snippets to v1.6.0
![https://i.bratteng.xyz/git/4pYMQv3IdY.png](https://i.bratteng.xyz/git/4pYMQv3IdY.png)

So, someone using brew, relies on brew for updating tools

**Comment by ChainsawBaby** [comment]
If I run `crypt -v`, I now get `Version 1.6.0`

**Comment by alexanderepstein** [comment]
Awesome I install to usr/local/bin so you should be able to update through homebrew or my application. I know if you install through homebrew that's where you update it though but I just didn't want my update method to break so that just in case someone does call it that way they aren't always returned with some error.

But it looks like it would work perfectly since we share the same install location. However if they are just symlinked I have to check if when I call ```-f usr/local/bin/tool``` that it would come back saying the file exists. It would then copy the new files to that directory and not necessarily symlink then so I would have to readjust for that.

Or I could avoid all of that and check if brew is installed on the machine and if it is just tell them to update through there.

The latter might be more plausible and make more sense because like you said if you install through homebrew you would probably update through there too.

**Comment by ChainsawBaby** [comment]
Just created a brew tap, so you can now install it like this
`brew install chainsawbaby/formula/bash-snippets`

**Comment by ChainsawBaby** [comment]
I'll see if I can come up with some tests for the brew formula

**Comment by alexanderepstein** [comment]
@ChainsawBaby awesome! Going to test it on my mac soon and will then add this to the readme. Any chance you could also copy ```bash-snippets.1``` to ```/usr/local/man/man1```. This will allow people to enter ```man bash-snippets``` and get information on all of the tools at once.

**Comment by ChainsawBaby** [comment]
@alexanderepstein Done, added man pages to the formula

**Comment by alexanderepstein** [comment]
Added to README here 36dabd4ee70cd882f732816c6bb52770994ca0e2 I do not inform the user of the possibility of flags such as ```--without-crypt``` due to the nature of the tests. Once the tests are testing functionality and not existence of crypt I will add that to the README as well.  

Hopefully will be able to retry adding this homebrew-core after the tests are improved upon and it has hit the 30 day notability requirement. Thanks for all of what you're doing :+1:

**Comment by alexanderepstein** [comment]
Not sure if you can use my tests but I have created a test suite for this repository using https://github.com/sstephenson/bats. All of the tests are located in the tests folder. I don't think you will be able to use them directly but they are tests that are ready to be ported to another language. The only tool that tests cannot run on is the taste tool because it requires an api key to be in the ~/.bash_profile

**Comment by mirfilip** [comment]
I have installed it as @ChainsawBaby pointed (from brew tap) and it seems it doesn't have all the scripts:
```sh
brew list chainsawbaby/formula/bash-snippets
/usr/local/Cellar/bash-snippets/1.13.0/bin/cheat
/usr/local/Cellar/bash-snippets/1.13.0/bin/crypt
/usr/local/Cellar/bash-snippets/1.13.0/bin/currency
/usr/local/Cellar/bash-snippets/1.13.0/bin/geo
/usr/local/Cellar/bash-snippets/1.13.0/bin/movies
/usr/local/Cellar/bash-snippets/1.13.0/bin/qrify
/usr/local/Cellar/bash-snippets/1.13.0/bin/short
/usr/local/Cellar/bash-snippets/1.13.0/bin/stocks
/usr/local/Cellar/bash-snippets/1.13.0/bin/taste
/usr/local/Cellar/bash-snippets/1.13.0/bin/weather
/usr/local/Cellar/bash-snippets/1.13.0/bin/ytview
/usr/local/Cellar/bash-snippets/1.13.0/share/man/man1/bash-snippets.1
```

cloudup, siteciphers, todo are missing.

**Comment by ChainsawBaby** [comment]
@mirfilip you are correct, give me a few minutes, I'll update the formula

**Comment by ChainsawBaby** [comment]
@mirfilip It should now be fixed. Could you please remove the brew, and install it again?
```
$ brew list chainsawbaby/formula/bash-snippets                                                                                                                                                  [10:38:43]
/usr/local/Cellar/bash-snippets/1.13.0/bin/cheat
/usr/local/Cellar/bash-snippets/1.13.0/bin/cloudup
/usr/local/Cellar/bash-snippets/1.13.0/bin/crypt
/usr/local/Cellar/bash-snippets/1.13.0/bin/currency
/usr/local/Cellar/bash-snippets/1.13.0/bin/geo
/usr/local/Cellar/bash-snippets/1.13.0/bin/movies
/usr/local/Cellar/bash-snippets/1.13.0/bin/qrify
/usr/local/Cellar/bash-snippets/1.13.0/bin/short
/usr/local/Cellar/bash-snippets/1.13.0/bin/siteciphers
/usr/local/Cellar/bash-snippets/1.13.0/bin/stocks
/usr/local/Cellar/bash-snippets/1.13.0/bin/taste
/usr/local/Cellar/bash-snippets/1.13.0/bin/todo
/usr/local/Cellar/bash-snippets/1.13.0/bin/weather
/usr/local/Cellar/bash-snippets/1.13.0/bin/ytview
/usr/local/Cellar/bash-snippets/1.13.0/share/man/man1/bash-snippets.1
```

**Comment by mirfilip** [comment]
@ChainsawBaby Yup, fixed, thx!

Just for other people stumbling upon this: neither of below seemed to update the tapped formula:
```
brew upgrade --force chainsawbaby/formula/bash-snippets
brew upgrade chainsawbaby/formula/bash-snippets
```
I neede to `uninstall` & `install --force`.

**Comment by ChainsawBaby** [comment]
@mirfilip I updated the formula again, and added a revision version to it. So anyone whom does an upgrade, will get the last upgrade of the brew.
So if you run `bubu` ( aliased for `brew update && brew outdated && brew upgrade && brew cleanup`), it will be updated

**Comment by alexanderepstein** [comment]
3 days away from being able to add this to homebrew core!

**Comment by retokromer** [comment]
It depends also on the popularity. We have our own tap at [AMIA Open Source](https://github.com/amiaopensource/homebrew-amiaos). The last formula that we moved to the core has been `qcli`, the CLI version of [QCTools](https://bavc.org/preserve-media/preservation-tools).

**Comment by alexanderepstein** [comment]
@retokromer is this not popular enough to add to homebrew core? I am asking sincerely since I really don't know :confused:. It seemed the main issue was the original pull request for adding this to the core was that the upstream repo was only 4 days old at the time, and the test part of the formula wasn't testing the functionality of the scripts.

**Comment by mirfilip** [comment]
@alexanderepstein Of course it is popular enough. There are 4969 stars on this repo. I know stars are not full story but I've seen plenty of niche tools added to homebrew-core.

Anyway, if you submit a PR to homebrew-core, there are people to decide whether it's mainstream enough to be included.

**Comment by alexanderepstein** [comment]
@mirfilip Okay glad to hear it :smile_cat: 

The only thing is that I am not supposed to be the one who submits a PR, and I know that the testing section of the formula be improved. I would work on the tests myself but I have no experience with Ruby.

From the [docs](http://docs.brew.sh/Acceptable-Formulae.html)
> We frown on authors submitting their own work unless it is very popular.

From the original [pull request](https://github.com/Homebrew/homebrew-core/pull/15107)
> the test in the test do block should exercise and verify the software's functionality.

**Comment by retokromer** [comment]
@alexanderepstein There are different criteria the maintainers consider. Yet by my remark I was **_not_** suggesting that you should not try, on the contrary please try!

**Comment by alexanderepstein** [comment]
Should be able to add to homebrew core starting today :tada:

**Comment by retokromer** [comment]
I updated this morning to v1.15.0. I guess you can copy&paste https://github.com/ChainsawBaby/homebrew-formula/pull/2 (if not done yet).

**Comment by alexanderepstein** [comment]
Yeah that should work, but according to homebrew 
>  We frown on authors submitting their own work unless it is very popular.

So I am not sure if i should be the one to submit the PR. If they would accept it from me I will gladly do it.

**Comment by retokromer** [comment]
Yes, you can copy&paste and submit it a PR.

**Comment by ChainsawBaby** [comment]
I will see if I have time to create a pull request to homebrew core tonight. I'm on vacation till Sunday

**Comment by retokromer** [comment]
@ChainsawBaby : It’s already [on track](https://github.com/Homebrew/homebrew-core/pull/16076): @alexanderepstein is doing it!

**Comment by alexanderepstein** [comment]
Just having trouble figuring out how to write the tests. And my build is failing because I am trying to copy my files over to directories that don't exist, how can I create these directories using Ruby?

**Comment by retokromer** [comment]
@alexanderepstein You are too fast!

**Comment by alexanderepstein** [comment]
@retokromer lol I try! Still need to write the tests however if either of you are willing and able to help

**Comment by alexanderepstein** [comment]
I only need to test the 3 most popular tools.

**Comment by alexanderepstein** [comment]
I wrote tests for the top 3 tools and it was [merged](https://github.com/Homebrew/homebrew-core/pull/16076) into homebrew-core :tada:

**Comment by alexanderepstein** [comment]
Thank you @ChainsawBaby and @retokromer for maintaining the tap :smiley_cat:

**Comment by ChainsawBaby** [comment]
@alexanderepstein Sweet! I'll keep my tap open for a few weeks in case someone doesn't notice the change
