### ISSUE TITLE
stocks not returning data

### ISSUE THREAD

**Issue by mj-2017** [alexanderepstein/Bash-Snippets#193]
'stocks' is no longer operational
* [ X] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
I'm using bash-snippets on an AWS Ubuntu 16.04.6 system.  Around Jun 14, 2019 my system started returning "Not a valid stock symbol" every time I executed 'stocks'.   Other bash-snippets scripts still operate wonderfully.

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [ X] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version: Ubuntu 16.04.6 LTS

**Comment by grdguez** [comment]
Having the same issue on my laptop running Ubuntu 19.04.

**Comment by tjstub** [comment]
I was passing through and did a bit of investigation on what's going on here.

IEX has sunset all third-party data from their v1 API (occurred June 1st, from what I can tell), and moved it to their IEX Cloud offering, which requires an account.  I assume this is what is causing the issue. The fix then for this issue is not straight forward. There are (from what I can tell) two possible paths.

1. Rewrite the stocks snippet to use account information to log into IEX cloud and upgrade to that API; or
2. Find a new API endpoint that can be accessed without an account, which might also incur a rewrite.

This is just an outsider taking a bit of time to see if it was an easy patch. Take it with a grain of salt.
