### ISSUE TITLE
Newton result field empty

### ISSUE THREAD

**Issue by ishaanbri** [alexanderepstein/Bash-Snippets#225]
**Issue Label:**
* [X] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [X] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
Linux centos 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Issue is concerning Newton. Similarly to the lyrics issue, the result field seems to be empty when typing in any combo of operation and expression.

![Screen Shot 2020-10-28 at 02 14 06](https://user-images.githubusercontent.com/46910415/97399328-55141180-18c3-11eb-9819-f46e45f7af35.jpg)

**Comment by navanchauhan** [comment]
This is because of the following line https://github.com/alexanderepstein/Bash-Snippets/blob/97a1c0d6358264a50ca0c6e221b74ea1cb72b372/newton/newton#L115

The new base url is `https://newton.now.sh/api/v2/`

I have opened a PR with the fix, you can just change the URL in your local installation till then.
