### ISSUE TITLE
Consider using double dashes style for options and flags in command line parameters

### ISSUE THREAD

**Issue by melezhik** [alexanderepstein/Bash-Snippets#48]
**Issue Label:**
* [ ] Bug
* [ ] New feature
* Enhancement
* [ ] New component

**Description:**

Many CLI utilities today have double dashes style when it comes to command line parameters:

    --foo-thing  

At least there are often alternatives:

    -f 
    --foo-thing

**Comment by alexanderepstein** [comment]
This is something I was going to do instead of allowing ```tool update``` it was going to be ```tool --update``` but after seeing other examples of how allowing options like this is achieved it seemed to like to much of a workaround that made the flow a little confusing to follow. Additionally this long options are not supported in the standard way on OSX and BSD based systems

**Comment by melezhik** [comment]
Ok, not that critical, just wanted to know your view on this, you may close this one if you want to.
