### ISSUE TITLE
Config File for API Key, URL, etc

### ISSUE THREAD

**Issue by CMiksche** [alexanderepstein/Bash-Snippets#58]
**Issue Label:**
* [ ] Bug
* [x] New feature
* [ ] Enhancement
* [ ] New component

**Description:**

The API-Key and URL in the stocks module are hardcoded in the file stocks/stocks.
`https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=$1&apikey=KPCCCRJVMOGN9L6T`

I haven't checked the other files yet, but it seems to me that a config file would be better. You could simply enter your own API Key and change the URL.

Only one API Key for all users could bring problems with limits and violations of terms ...

**Comment by alexanderepstein** [comment]
I may look into adding this.

For now the idea was don't have the user enter any API keys unless it is logical for it to be on a user to suer basis. This is why the taste script requires an API key and i don't just hardcode my key in because the recommendations are supposed to improve based on the users previous searches. Stocks however don't change no matter what user is accessing the information.

**Comment by alexanderepstein** [comment]
Don't think I will be adding this for now, If I get any API limitation issues I will reopen this issue and add a config file.
