### ISSUE TITLE
ytview cannot play videos with ads

### ISSUE THREAD

**Issue by karanrajpal14** [alexanderepstein/Bash-Snippets#68]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**

### If its a bug make sure to include this section.
**OS and OS version:**
* [ ] Mac
* [ ] Linux 32 Bit
* [x] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
Ubuntu 17.04

Can't get the ytview to work for me. I run `ytview linkin park` and select the first video which makes an  error pop up saying:
```
Your input can't be opened:
VLC is unable to open the MRL 'https://r4---sn-ci5gup-cags.googlevideo.com/videoplayback?ei=Z6tpWcLRIMm1oAPrirTwDw&requiressl=yes&itag=43&id=o-APaAaOjNS53wh_4zy7keT4WXzPo65QRHrYKiZyFHVJlF&dur=0.000&gir=yes&mm=31&mn=sn-ci5gup-cags&pcm2cms=yes&source=youtube&clen=16873382&ip=106.201.41.213&ms=au&mt=1500097292&mv=m&lmt=1365509526128018&expire=1500118983&ratebypass=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mime=video%2Fwebm&key=yt6&ipbits=0&initcwndbps=1012500&pl=19&signature=D6C62835742E9DAD988BD9811C466B7C0622CC6F.8D32C15D02389B257F692FC69AFAFB5C456EB003'. Check the log for details.
```

Any idea what's going wrong?

**Comment by monokh** [comment]
I had a look at this to try to fix it. The bash script is working as expected and all it does is pass the youtube url. The problem is with VLC which is unable to start the stream. 
The pattern i saw is that usually these are videos that have ads. Either way i think this one is for VLC or to implement another method of playing youtube videos?

**Comment by alexanderepstein** [comment]
I have noticed this as well and like @monokh said I am pretty sure it is only for videos with ads. I don't think any video streaming player will be able to handle this.

**Comment by monokh** [comment]
@alexanderepstein I was checking the options, unlikely there is a solution using only the media player.
VLC's youtube extension is brittle and is not kept up to date as youtube modifies things on their end however [youtube-dl](https://github.com/rg3/youtube-dl/) does a very good job at this. 

2 options there is:

- Save to tmp location and send file to `vlc`
- Stream directly to vlc `youtube-dl "https://www.youtube.com/watch?v=kXYiU_JCYtU" -o - | vlc -`

Although i am reminded of this part of the description of the project:

> A collection of small bash scripts for heavy terminal users **with no dependencies**

So i'm not sure if this kind of solution is acceptable or not 😉

**Comment by alexanderepstein** [comment]
Hmm the first option seems viable if I or anyone else can find a way to download the video without a dependency such as ```youtube-dl``` then it will be implemented. The issue being that if the video is large it will be a very long time until you can view the video whereas streaming circumvents this problem.

**Comment by karanrajpal14** [comment]
I'm a bit curious now. There are a few apps on Android such as [NewPipe](https://github.com/TeamNewPipe/NewPipe) which can stream YouTube videos without ads. Any idea how they're achieving this? Maybe something similar can be done here?

**Comment by monokh** [comment]
If the youtube video can be downloaded, there's no reason why it couldn't be streamed to VLC directly. You could use an online youtube downloader. The problem is that these sites are often short lived. 

All the youtube stream/download apps implement the same method to figure out the real video url of a youtube video. The issue is that this is often changing as youtube changes it's backend to prevent this sort of thing - this is why whole libraries (like `youtube-dl`) have frequent development and maintenance to deal with these changes. 

I don't realistically see being able to develop a bash script to do this reliably as part of this project - it would just need too much maintenance and dedication.

**Comment by alexanderepstein** [comment]
@monokh  
I strongly agree with 
> I don't realistically see being able to develop a bash script to do this reliably as part of this project - it would just need too much maintenance and dedication. 

The idea of these scripts is to be simplistic and it would be to hard to account for this due to the nature of youtube trying to stop people from doing just that.
