### ISSUE TITLE
todo not working

### ISSUE THREAD

**Issue by rsouthpaw** [alexanderepstein/Bash-Snippets#70]
**Issue Label:**
* [x] Bug
* [ ] New feature
* [ ] Enhancement
* [ ] New component

**Description:**
while all other commands are working perfectly fine, todo command gives error.
-bash : todo: command not found

**OS and OS version:**
* [x] Mac
* [ ] Linux 32 Bit
* [ ] Linux 64 Bit
* [ ] Windows 32 Bit
* [ ] Windows 64 Bit

OS Version:
macOS SIerra

**Comment by alexanderepstein** [comment]
Can you tell me what version of bash-snippets you are using by running any working tool with the -v option?

**Comment by alexanderepstein** [comment]
If you are using homebrew I believe that the install has just not been updated.

 Otherwise If i had to guess you ran the updater but not a new install. Whenever you update the tool only updates installed tools and will never install any tool that is not already currently present on the system. So upgrading from 1.12.0 to 1.13.0 will not install ```todo``` for you. Recloning the repo and running the ```install.sh``` file again will give you the ability to install ```todo```

**Comment by rsouthpaw** [comment]
Yes, I used homebrew earlier. Now I have installed todo using install.sh. It works now. Thanks! 👍

**Comment by alexanderepstein** [comment]
No problem, glad it works now!
