### ISSUE TITLE
Todo fails to add a new task when using -a"foo" in bash

### ISSUE THREAD

**Issue by mirfilip** [alexanderepstein/Bash-Snippets#83]
**Issue Label:**
* [x] Bug

**Description:**
When adding a new todo task, the notation `todo -a 'foo'` works fine. When using `todo -a'foo'` or `todo -a"foo"`, the exit code is `0` but the task is not added:
```sh
todo -c
todo -g
// nothing
todo -a'foo'
echo $? 
//0
todo -g
// still nothing
```

Usually *nix tools allow a space between an option and an argument. Regardless, if that's not supported, exit code 0 shouldn't be returned as operation hasn't succeeded.

### If its a bug make sure to include this section.
**OS and OS version:**
* [x] Mac

OS Version: 10.12.5

### Additional info:
Bash version: GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)
Same behaviour with system bash: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

**Comment by alexanderepstein** [comment]
Just to clarify
> Usually *nix tools allow a space between an option and an argument.

This tool does allow a space between an option and an argument. And it seems thats what you mean because the rest of the issue is based around the fact that it doesn't work without the space. You are correct this is not supported, the problem is when you run ```todo -a Some task``` the way I grab the arguments is ```"${*:2}"``` which grabs all arguments starting with ```$2``` all the way up to ```$#```. Running the task ```todo -a'foo hello'``` doesn't do anything, returns no error and doesn't have the correct exit code. However when you run ```todo -afoo hello``` that will actually work but it will only add the task ```hello``` and not the task ```foo hello```. 

I will look into determining the best solution to fix this.

**Comment by mirfilip** [comment]
@alexanderepstein I see. 
>doesn't do anything, returns no error and doesn't have the correct exit code because it never sees the option as -a but as an argument of -afoo

In my view, this should raise an error that "afoo" argument is not supported and return non-zero exit code.

**Comment by alexanderepstein** [comment]
> In my view, this should raise an error that "afoo" argument is not supported and return non-zero exit code.
 I agree with you here and have added checks for this case in this commit 935c92052d0176ceb3c7908b34b5ccadb1bf35d7

**Comment by alexanderepstein** [comment]
Released in <a href="https://github.com/alexanderepstein/Bash-Snippets/releases/tag/v1.14.0">Version 1.14.0</a>
